# SPDX-FileCopyrightText: Copyright (c) 2025 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

_target_: navsim.agents.gtrs_aug.gtrs_aug_agent.GTRSAugAgent
_convert_: 'all'
metrics:
  - no_at_fault_collisions
  - drivable_area_compliance
  - time_to_collision_within_bound
  - ego_progress
  - driving_direction_compliance
  - lane_keeping
  - traffic_light_compliance
  - history_comfort

config:
  _target_: navsim.agents.gtrs_aug.hydra_config_aug.HydraConfigAug
  _convert_: 'all'
  vocab_path: ${oc.env:NAVSIM_DEVKIT_ROOT}/traj_final/8192.npy
  ckpt_path: hydra_8192_ckpt
  vocab_size: 8192
  lidar_seq_len: 4
  sigma: 0.5
  trajectory_imi_weight: 1.0
  progress_weight: 2.0

  normalize_vocab_pos: True

  camera_width: 2048
  camera_height: 512
  img_vert_anchors: 16
  img_horz_anchors: 64

  backbone_type: 'vov'
  vov_ckpt: ${oc.env:OPENSCENE_DATA_ROOT}/models/dd3d_det_final.pth
  lr_mult_backbone: 1.0

  trajectory_sampling:
    _target_: nuplan.planning.simulation.trajectory.trajectory_sampling.TrajectorySampling
    _convert_: 'all'
    time_horizon: 4
    interval_length: 0.1

  # robust settings
  training: True

  ego_perturb:
    _target_: navsim.agents.gtrs_aug.hydra_config_aug.EgoPerturbConfig
    _convert_: 'all'
    mode: load_from_offline  # 'fixed' or 'load_from_offline'
    ensemble_aug: false
    offline_aug_file: ${oc.env:NAVSIM_TRAJPDM_ROOT}/random_aug/rot_30-trans_0-va_0-p_0.5-ensemble.json
    rotation:
      _target_: navsim.agents.gtrs_aug.hydra_config_aug.RotationConfig
      enable: true
      fixed_angle: 0.0
      offline_aug_angle_boundary: 30
      change_camera: false
      crop_from_panoramic: true
    va:
      _target_: navsim.agents.gtrs_aug.hydra_config_aug.VAConfig
      enable: false
      offline_aug_boundary: 0.0
  
  camera_problem:
    _target_: navsim.agents.gtrs_aug.hydra_config_aug.CameraProblemConfig
    shutdown_enable: false
    shutdown_mode: 1
    shutdown_probability: 0.0
    noise_enable: false
    noise_percentage: 0.0
    
    gaussian_enable: false
    gaussian_mode: load_from_offline
    gaussian_probability: 1.0
    gaussian_min_std: 0.05
    gaussian_max_std: 0.25
    gaussian_offline_file: "ccc.json"

    weather_enable: False
    weather_aug_mode: random
    fog_prob: 0.25
    rain_prob: 0.25
    snow_prob: 0.25

  only_ori_input: false
  student_rotation_ensemble: 3
  ori_vocab_pdm_score_full_path: ${oc.env:NAVSIM_TRAJPDM_ROOT}/ori/navtrain_8192.pkl
  aug_vocab_pdm_score_dir: ${oc.env:NAVSIM_TRAJPDM_ROOT}/random_aug/rot_30-trans_0-va_0-p_0.5-ensemble/split_pickles
  weakly_supervised_imi_learning: false
  pdm_close_traj_for_augmented_gt: false
  traj_smoothing: false

  only_imi_learning: false

  soft_label_traj: 'first'
  soft_label_imi_diff_thresh: 1.0
  soft_label_score_diff_thresh: 0.15

  use_rotation_loss: false
  use_mask_loss: false

  refinement:
    _target_: navsim.agents.gtrs_aug.hydra_config_aug.RefinementConfig
    use_multi_stage: true
    num_refinement_stage: 1
    stage_layers: 3
    topks: 256
    use_mid_output: true
    use_offset_refinement: true
    use_separate_stage_heads: true
  
  inference:
    _target_: navsim.agents.gtrs_aug.hydra_config_aug.InferConfig
    model: teacher
    use_aug: true
  
  lab:
    _target_: navsim.agents.gtrs_aug.hydra_config_aug.LabConfig
    check_top_k_traj: false
    num_top_k: 64
    test_full_vocab_pdm_score_path: "aaa"
    use_first_stage_traj_in_infer: false
    change_loss_weight: false
    use_imi_learning_in_refinement: true
    adjust_refinement_loss_weight: false
    adjust_refinement_score_weight: false
    ban_soft_label_loss: false
    optimize_prev_frame_traj_for_ec: false
    refinement_metrics: 'all'
    use_higher_res_feat_in_refinement: false
    use_cosine_ema_scheduler: false
    ema_momentum_start: 0.99


checkpoint_path: null
lr: 1e-4