reactive:
  _target_: navsim.traffic_agents_policies.navsim_IDM_traffic_agents.NavsimIDMTrafficAgents
  _convert_: all

  idm_agents_observation:
    _target_: navsim.planning.simulation.observation.navsim_idm_agents.NavsimIDMAgents
    _convert_: 'all'
    target_velocity: 10         # Desired velocity in free traffic [m/s]
    min_gap_to_lead_agent: 1.0  # Minimum relative distance to lead vehicle [m]
    headway_time: 1.5           # Desired time headway. The minimum possible time to the vehicle in front [s]
    accel_max: 1.0              # maximum acceleration [m/s^2]
    decel_max: 2.0              # maximum deceleration (positive value) [m/s^2]
    open_loop_detections_types: [] # ["PEDESTRIAN", "BARRIER", "CZONE_SIGN", "TRAFFIC_CONE", "GENERIC_OBJECT"]  # Open-loop detections to include
    minimum_path_length: 20     # [m] The minimum path length to maintain
    planned_trajectory_samples: null # Number of elements to sample for the planned trajectory.
    planned_trajectory_sample_interval: null # [s] The time interval of sequence to sample from.
    radius: 100                 # [m] Only agents within this radius around the ego will be simulated.
    add_open_loop_parked_vehicles: true
    idm_snap_threshold: 3.0  # [m] The threshold distance to snap agents to the IDM model
